### ISSUE TITLE
Most XML files in "Data" table differ from "distribution" in json files

### ISSUE THREAD

**Issue by acouch** [USAID/Feedback#14]
Many if not most of the XML files in the "Data" column differ from the XML file in the individual dataset json files and the files listed on data.json

For example, "Dollars to Results, Kenya" lists an XML file: 
* http://www.usaid.gov/opengov/developer/datasets/D2RKenya2012.xml ("Data" column)
* http://www.usaid.gov/sites/default/files/D2RKenya2012.xml (json file and data.json)

**Comment by cmurphyUSAID** [comment]
The full dataset for all countries is now http://results.usaid.gov/data/USAID-DTR-fulldataset.zip

The direct link on www.usaid.gov/data and the url in the json file now match.
