### ISSUE TITLE
portfolio.usaid.gov Download Functionality

### ISSUE THREAD

**Issue by joshuacpowell** [USAID/Feedback#15]
Will there be access to the raw data underpinning the portfolio.usaid.gov page? If so, when will the be available?

**Comment by jksmith6** [comment]
Good morning Josh. 

Unfortunately at this time the portfolio.usaid.gov page is broken. There is no way for us to access any of the raw data underpinning the portfolio as the site is no longer accessible. 

We would like for you to please accept our apology. We recognize our absence on GitHub and our team is working to ensure a quick response to all open questions regarding USAID open data on the site in addition to providing a swift response to all new questions.

We would also like to update you concerning our new Development Data Library (DDL). It was launched on November 13th. We encourage you to check it out at your earliest convenience. Additionally, please feel free to contact the USAID Data Services team at dataservices@usaid.gov.

Kind regards,
The USAID Data Services Team

Closed #15
