### ISSUE TITLE
Codebook links in JSON files broken for Feed the Future Data

### ISSUE THREAD

**Issue by lhughes02** [USAID/Feedback#19]
In the Feed the Future Baseline Household surveys, one of the links within the JSON files to the codebooks does not work:

Uganda: http://www.usaid.gov/opengov/developer/datasets/Uganda%202013%20FTF%20ZOI%20PBS%20Public%20Release%20Codebook%20-%2020140421.xls

Thanks! 

- Laura

**Comment by sdepies** [comment]
close #19 Hello Laura,

The sight and the address have been updated. The code book can now be found at https://www.usaid.gov/opengov/developer/datasets/UgandaFTFCodebook.xls
