### ISSUE TITLE
Ghana FtF .zip link broken

### ISSUE THREAD

**Issue by flaneuse** [USAID/Feedback#20]
When trying to access the FtF Ghana data from the /data page, the link to the zip file is broken: 
"The requested page "/sites/default/files/USAID_FTF-Ghana_Docs.zip" could not be found."

It looks like it should be: "http://www.usaid.gov/opengov/developer/datasets/ghana-feed-the-future-dataset.zip"

**Comment by cmurphyUSAID** [comment]
Thanks for the catch.

You were correct.

The link is fixed, now.
