### ISSUE TITLE
No Data Dictionary for South Sudan Baseline Survey of Ag. Practices

### ISSUE THREAD

**Issue by tzearley** [USAID/Feedback#21]
The link to the data dictionary appears to be broken or the file is missing.

http://www.usaid.gov/datasets/SouthSudanDataDictionary.json

**Comment by bpushed** [comment]
Thank you.  We have received your request and are looking into a fix.

**Comment by sdepies** [comment]
The site has been updated the data dictionary json is now located at http://www.usaid.gov/sites/default/files/SouthSudanDataDictionary.json
