### ISSUE TITLE
Nepal FTF Baseline Survey download

### ISSUE THREAD

**Issue by jharpster** [USAID/Feedback#23]
There is an error on the download page for the Nepal baseline survey data at: https://www.usaid.gov/data/dataset/92fa242f-07b3-4ec4-9e98-84ab09e1078b

The HTTP is in twice: http://http//www.usaid.gov/opengov/developer/datasets/Nepal_CSVs.zip

**Comment by bpushed** [comment]
Thank you for the heads up.  Should be rectified.
