### ISSUE TITLE
My COR is not receiving Partner Account request

### ISSUE THREAD

**Issue by nopetroni** [USAID/Feedback#40]
We are ready to upload datasets to DDL but cannot do so until we have a Partner Account. We have repeatedly requested a Partner Account but our COR Paola Buendia Paola (pbuendia@usaid.gov) has not received any requests to approve our Partner Account. Could you please make sure she receives our request for a Partner Account?

Thank you so much, Natalia Petroni

**Comment by lenaknezevic** [comment]
Hi Natalia,

Thank you for reaching out to the USAID Data Services team. We have been experiencing issues with our partner account request form, so form submissions have not been coming through to our inbox. Please email us at dataservices@usaid.gov with the following information so we can ask your AOR/COR to approve your request for a partner account:

Submitter Name: [Partner User First Name/Last Name]
Submitting Organization: [Name of submitting organization entered during the request]
Submitting Organization DUNS Number: [Organization DUNS Number]
USAID Operating Unit: USAID operating unit name
Award Number: [Award number for the project]
COR/AOR Name: [Name of COR/AOR]
COR/AOR Email: [Email address of COR/AOR]

Best,
Lena
