### ISSUE TITLE
Newspaper subscription passwords

### ISSUE THREAD

**Issue by lazurduy** [USAID/Feedback#44]
Hi there, 

I just got a mail telling me that my free Washington Post subscription will end. Does USAID have an account we can access? It would be great to be able to access the NYT and Wall Street Journal as well. Thanks.

**Comment by MorganDaniels** [comment]
Hello, Your request has been forwarded to USAID's Library team, who will answer you via email.  This GitHub page is managed by a different group, which administers the Development Data Library, USAID's data repository.  For future Library team requests please email dataservicesrequest at usaid.gov.  Regarding the specific periodicals you asked about, the Library does not manage agency-wide subscriptions to these publications, but will tell you more about the methods they do provide to access content in a forthcoming email message.
