### ISSUE TITLE
Request for Afghanistan education datasets

### ISSUE THREAD

**Issue by KatataK** [USAID/Feedback#7]
Request to opendata@usaid.gov:

I have been looking for data sets related to education in Afghanistan. I
wanted to write some econometric papers related to Afghanistan but cannot
find any datasets. Any help would be greatly appreciate.

Response:
Thank you for your interest in education data sets for Afghanistan.  We have consulted with USAID subject matter experts regarding your inquiry and do not have data that is immediately available for publication.  However, USAID is continuously working to expand, enrich, and open its data inventory in accordance with the Executive Order and OMB Policy (M-13-13) on Open Data.  We encourage you to continue to visit www.usaid.gov/data for updates as they become available. You may also access the JSON version of USAID's Public Data Listing at www.usaid.gov/data.json.  Updates take place, at minimum, on a quarterly basis.  

We would also encourage you to consult www.data.gov and to log your request on USAID's GitHub site and Open Data Stack Exchange so that you can engage with others who are using or seeking similar kinds of data. 

We very much appreciate your interest in open data at USAID.

Sincerely,

The USAID Open Data Team

**Comment by jksmith6** [comment]
Closes #7
